version: 2
updates:
  - package-ecosystem: docker
    directory: /ci-alpine
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "github-actions"
      - "CI"