##################################################
## Node image with integrated Firefox instance. ##
##      To run tests in headless browser.       ##
##################################################

## Defaults:
## Node version: 16.13(LTS)
## Alpine version: 3.15
## Firefox version: 94.0-r0
## https://pkgs.alpinelinux.org/packages?name=firefox&branch=v3.15

ARG node_image='node:16.13-alpine3.15'

FROM $node_image AS base

WORKDIR /home/node
COPY . .

# proxy if you build behind the proxy
ARG http_proxy_string
ARG https_proxy_string

# Installs latest Chromium package.
RUN  \
    chmod -R 755 ./build.sh \
    && https_proxy=${https_proxy_string} \
        HTTPS_PROXY=${https_proxy_string} \
        http_proxy=${http_proxy_string} \
        HTTP_PROXY=${http_proxy_string} \
            ./build.sh \
    # cleanup
    && rm -rf build.sh
